ALTER TABLE activities
    ADD COLUMN version INT DEFAULT 0 NOT NULL;
ALTER TABLE groups
    ADD COLUMN version INT DEFAULT 0 NOT NULL;
ALTER TABLE questions
    ADD COLUMN version INT DEFAULT 0 NOT NULL;
ALTER TABLE template
    ADD COLUMN version INT DEFAULT 0 NOT NULL;
ALTER TABLE users
    ADD COLUMN version INT DEFAULT 0 NOT NULL;